Repository CogniBuild/Campus.Master, pull requests merged in 2021-01, with the labels that each got.

#59 Missing configuration jest
  Src/Campus.Master.API/UI/angular.json
  Src/Campus.Master.API/UI/jest.config.js
  Src/Campus.Master.API/UI/src/test.ts
  Src/Campus.Master.API/UI/tsconfig.spec.json
Labels: enhancement, refactoring

#61 Remove task manager components
  Src/Campus.Master.API/UI/angular.json
  Src/Campus.Master.API/UI/src/app/app-routing.module.ts
  Src/Campus.Master.API/UI/src/app/app.module.ts
  Src/Campus.Master.API/UI/src/app/auth/registration/registration.component.ts
  Src/Campus.Master.API/UI/src/app/auth/sing-in/sing-in.component.ts
  Src/Campus.Master.API/UI/src/app/core/left-sidebar/left-sidebar.component.html
  Src/Campus.Master.API/UI/src/app/core/left-sidebar/left-sidebar.component.sass
  Src/Campus.Master.API/UI/src/app/core/left-sidebar/left-sidebar.component.ts
  Src/Campus.Master.API/UI/src/app/core/sign-in.service.ts
  Src/Campus.Master.API/UI/src/app/data/dao/impl/CategoryDAOArray.ts
  Src/Campus.Master.API/UI/src/app/data/dao/impl/PriorityDAOArray.ts
  Src/Campus.Master.API/UI/src/app/data/dao/impl/StatusDAOArray.ts
  Src/Campus.Master.API/UI/src/app/data/dao/impl/TaskDAOArray.ts
  Src/Campus.Master.API/UI/src/app/data/dao/interface/CategoryDAO.ts
  Src/Campus.Master.API/UI/src/app/data/dao/interface/CommonDAO.ts
  Src/Campus.Master.API/UI/src/app/data/dao/interface/PriorityDAO.ts
  Src/Campus.Master.API/UI/src/app/data/dao/interface/StatusDAO.ts
  Src/Campus.Master.API/UI/src/app/data/dao/interface/TaskDAO.ts
  Src/Campus.Master.API/UI/src/app/data/testData.ts
  Src/Campus.Master.API/UI/src/app/dialog/edit-task-dialog/edit-task-dialog.component.html
  Src/Campus.Master.API/UI/src/app/dialog/edit-task-dialog/edit-task-dialog.component.sass
  Src/Campus.Master.API/UI/src/app/dialog/edit-task-dialog/edit-task-dialog.component.ts
  Src/Campus.Master.API/UI/src/app/models/task-list/priority.ts
  Src/Campus.Master.API/UI/src/app/models/task-list/project.ts
  Src/Campus.Master.API/UI/src/app/models/task-list/status.ts
  Src/Campus.Master.API/UI/src/app/models/task-list/task.ts
  Src/Campus.Master.API/UI/src/app/services/data-handler.service.ts
  Src/Campus.Master.API/UI/src/app/services/project.service.ts
  Src/Campus.Master.API/UI/src/app/services/sort-date.service.ts
  Src/Campus.Master.API/UI/src/app/shared/models/state-transfer.ts
  Src/Campus.Master.API/UI/src/app/views/task-list-layout/projects/projects.component.html
  Src/Campus.Master.API/UI/src/app/views/task-list-layout/projects/projects.component.sass
  Src/Campus.Master.API/UI/src/app/views/task-list-layout/projects/projects.component.ts
  Src/Campus.Master.API/UI/src/app/views/task-list-layout/task-list-layout/task-list-layout.component.html
  Src/Campus.Master.API/UI/src/app/views/task-list-layout/task-list-layout/task-list-layout.component.sass
  Src/Campus.Master.API/UI/src/app/views/task-list-layout/task-list-layout/task-list-layout.component.ts
  Src/Campus.Master.API/UI/src/app/views/tasks_board/right-sidebar/right-sidebar.component.html
  Src/Campus.Master.API/UI/src/app/views/tasks_board/right-sidebar/right-sidebar.component.sass
  Src/Campus.Master.API/UI/src/app/views/tasks_board/right-sidebar/right-sidebar.component.ts
  Src/Campus.Master.API/UI/src/app/views/tasks_board/stat/stat-card/stat-card.component.html
  Src/Campus.Master.API/UI/src/app/views/tasks_board/stat/stat-card/stat-card.component.sass
  Src/Campus.Master.API/UI/src/app/views/tasks_board/stat/stat-card/stat-card.component.ts
  Src/Campus.Master.API/UI/src/app/views/tasks_board/stat/stat.component.html
  Src/Campus.Master.API/UI/src/app/views/tasks_board/stat/stat.component.sass
  Src/Campus.Master.API/UI/src/app/views/tasks_board/stat/stat.component.ts
  Src/Campus.Master.API/UI/src/app/views/tasks_board/task-board-layout/task-board-layout.component.html
  Src/Campus.Master.API/UI/src/app/views/tasks_board/task-board-layout/task-board-layout.component.sass
  Src/Campus.Master.API/UI/src/app/views/tasks_board/task-board-layout/task-board-layout.component.ts
  Src/Campus.Master.API/UI/src/app/views/tasks_board/task/task.component.html
  Src/Campus.Master.API/UI/src/app/views/tasks_board/task/task.component.sass
  Src/Campus.Master.API/UI/src/app/views/tasks_board/task/task.component.ts
  Src/Campus.Master.API/UI/src/app/views/user-page-layout/user-page-layout.component.html
  Src/Campus.Master.API/UI/tsconfig.json
Labels: refactoring

#66 Sign in service tests
  Src/Campus.Master.API/UI/src/app/auth/shared/services/registration.service.spec.ts
  Src/Campus.Master.API/UI/src/app/core/sign-in.service.spec.ts
Labels: tests

#67 Sign-in page 500 error message does not appear in toastr (+ messages localization)
  Src/Campus.Infrastructure.Business/Services/ProfileService.cs
  Src/Campus.Master.API/UI/src/app/auth/registration/registration.component.html
  Src/Campus.Master.API/UI/src/app/auth/registration/registration.component.spec.ts
  Src/Campus.Master.API/UI/src/app/auth/registration/registration.component.ts
  Src/Campus.Master.API/UI/src/app/auth/sing-in/sing-in.component.html
  Src/Campus.Master.API/UI/src/app/auth/sing-in/sing-in.component.ts
  Src/Campus.Master.API/UI/src/app/core/guards/can-activate-dashboard.guard.ts
  Src/Campus.Master.API/UI/src/app/shared/services/index.ts
  Src/Campus.Master.API/UI/src/app/shared/services/locale.service.spec.ts
  Src/Campus.Master.API/UI/src/app/shared/services/locale.service.ts
  Src/Campus.Master.API/UI/src/app/shared/shared.module.ts
  Src/Campus.Master.API/UI/src/assets/locale/en.json
  Src/Campus.Master.API/UI/src/assets/locale/ua.json
  Test/Campus.Master.IntegrationTests/ProfileController/CreateProfileTests.cs
Labels: bug, refactoring, tests
